version: '3.1'

services:
  tasks-lists-back:
    build: ./back
    image: tasks-lists-back:0.0.0
    hostname: tasks-lists-back
    container_name: tasks-lists-back
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=tasks
      - MYSQL_USER=tasks
      - MYSQL_PASSWORD=tasks
    ports:
      - "3000:3000"

  tasks-lists-front:
    build: ./front
    image: tasks-lists-front:0.0.0
    hostname: tasks-lists-front
    container_name: tasks-lists-front
    volumes:
      - ./front/dist:/usr/src/app/dist
    command: "npm run build"

  mysql:
    image: "mysql:5.7.22"
    hostname: "mysql"
    container_name: "mysql"
    environment:
      - SERVICE_NAME=mysql
      - MYSQL_DATABASE=tasks
      - MYSQL_USER=tasks
      - MYSQL_PASSWORD=tasks
      - MYSQL_ROOT_PASSWORD=c2Xq5vdÇz?KR62AR
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/model.sql:ro
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: ['--lower_case_table_names=1', '--general-log=1', '--general-log-file=/var/log/mysql/general-log.log']

    # winpty docker exec -ti mysql tail -f /var/log/mysql/general-log.log
    # jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&useSSL=false

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:4.7"
    hostname: "phpmyadmin"
    container_name: "phpmyadmin"
    environment:
      - SERVICE_NAME=phpmyadmin
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=c2Xq5vdÇz?KR62AR
    ports:
      - "8081:80"
    depends_on:
      - mysql
